Integrate Mayhem
mayhemheroes/opa pull request #1
Opened 2022-10-31 02:52 UTC by 4812571

Integrated Mayhem, a fuzz testing solution by ForAllSecure. Mayhem is targeting existing fuzz tests in the repository

2022-12-23 04:04 UTC, xansec requested changes
Please make the requested changes.

2022-12-23 04:04 UTC, xansec commented on mayhem/Dockerfile
> +# Copyright 2020 Google Inc.
Address the copyright, and add a package stage.

2022-12-23 04:04 UTC, xansec commented on mayhem/build.sh
> +#!/bin/bash -eu
No need for a build script for just one line.

2023-01-24 20:51 UTC, xansec requested changes
These fuzz targets still need to be renamed, even if we are accepting OSS-Fuzz integrations. Please make the requested changes.

2023-01-25 04:38 UTC, 4812571 commented
The fuzz targets have been renamed.

2023-01-25 05:21 UTC, 4812571 commented
I fixed those up - the action is reporting as failed, but the run still works as normal - see https://github.com/mayhemheroes/relay/pull/1 for another case of this problem.

2023-01-25 16:42 UTC, xansec approved these changes
LGTM!

2023-01-25 16:42 UTC, merged